# Generated by Django 5.2.7 on 2026-06-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_failed_login_count_user_last_login_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('invited', 'Invited')], default='invited', max_length=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('invited', 'Invited')], default='invited', max_length=12),
        ),
    ]
