# Generated by Django 5.2.7 on 2025-10-12 07:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('ka_sa_num', models.CharField(max_length=100, unique=True)),
                ('dob_bs', models.CharField(max_length=10)),
                ('dob_ad', models.DateField()),
                ('jobstartdate_bs', models.CharField(max_length=10)),
                ('jobstartdate_ad', models.DateField()),
                ('current_position_date_bs', models.CharField(max_length=10)),
                ('current_position_date_ad', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('working_directorate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organizations.directorate')),
                ('working_ministry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organizations.ministry')),
                ('working_office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organizations.office')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfficeTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date_bs', models.CharField(max_length=10)),
                ('end_date_bs', models.CharField(blank=True, max_length=10, null=True)),
                ('start_date_ad', models.DateField()),
                ('end_date_ad', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_history', to='employees.employee')),
                ('from_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to='organizations.office')),
                ('to_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='organizations.office')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
