# Generated by Django 5.2.7 on 2025-10-14 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officetransfer',
            old_name='start_date_ad',
            new_name='transfer_date_ad',
        ),
        migrations.RenameField(
            model_name='officetransfer',
            old_name='start_date_bs',
            new_name='transfer_date_bs',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='working_directorate',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='working_ministry',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='working_office',
        ),
        migrations.RemoveField(
            model_name='officetransfer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='officetransfer',
            name='end_date_ad',
        ),
        migrations.RemoveField(
            model_name='officetransfer',
            name='end_date_bs',
        ),
        migrations.RemoveField(
            model_name='officetransfer',
            name='from_office',
        ),
        migrations.RemoveField(
            model_name='officetransfer',
            name='to_office',
        ),
        migrations.RemoveField(
            model_name='officetransfer',
            name='updated_at',
        ),
    ]
