# Generated by Django 5.2.7 on 2025-10-14 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_rename_start_date_ad_officetransfer_transfer_date_ad_and_more'),
        ('organizations', '0002_remove_office_directorate_remove_office_ministry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='working_organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='officetransfer',
            name='from_organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='officetransfer',
            name='to_organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='officetransfer',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
    ]
