# Generated by Django 5.2.7 on 2025-10-15 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_working_organization_and_more'),
        ('organizations', '0002_remove_office_directorate_remove_office_ministry_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officetransfer',
            old_name='transfer_date_ad',
            new_name='from_date_ad',
        ),
        migrations.RenameField(
            model_name='officetransfer',
            old_name='transfer_date_bs',
            new_name='from_date_bs',
        ),
        migrations.AddField(
            model_name='officetransfer',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='officetransfer',
            name='to_date_ad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officetransfer',
            name='to_date_bs',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='officetransfer',
            name='from_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='officetransfer',
            name='to_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to='organizations.organization'),
        ),
    ]
