# Generated by Django 5.2.7 on 2025-10-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_beneficiary_name_employee_father_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='citizenship_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='permanent_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
