# Generated by Django 5.2.7 on 2025-10-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0006_employee_citizenship_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="officetransfer",
            name="from_organization",
        ),
        migrations.AddField(
            model_name="employeestatushistory",
            name="remarks",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="officetransfer",
            name="status",
            field=models.CharField(
                choices=[
                    ("TRANSFERRED", "Saruwa"),
                    ("KAAJ", "Kaaj"),
                    ("PROMOTED", "Badhuwa"),
                    ("RECRUITED", "Niyukti"),
                    ("OTHER", "Anya"),
                ],
                default="TRANSFERRED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="officetransfer",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
    ]
