# Generated by Django 5.2.7 on 2025-10-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0007_remove_officetransfer_from_date_ad_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "पुरुष"), ("Female", "महिला"), ("Other", "अन्य")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="gender_other",
            field=models.CharField(
                blank=True,
                help_text="Specify gender if 'Other' is selected.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="officetransfer",
            name="status",
            field=models.CharField(
                choices=[
                    ("TRANSFERRED", "सरुवा"),
                    ("KAAJ", "काज"),
                    ("PROMOTED", "बढुवा"),
                    ("RECRUITED", "नियुक्ति"),
                    ("OTHER", "अन्य"),
                ],
                default="TRANSFERRED",
                max_length=20,
            ),
        ),
    ]
