# Generated by Django 5.2.7 on 2025-10-28 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0008_remove_officetransfer_from_date_ad_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="officetransfer",
            name="decision_date_ad",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="officetransfer",
            name="decision_date_bs",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="officetransfer",
            name="initiated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="initiated_transfers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="officetransfer",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="officetransfer",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_transfers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="officetransfer",
            name="verified_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
