# Generated by Django 5.2.7 on 2026-06-26 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_remove_officetransfer_from_date_ad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officetransfer',
            name='from_date_ad',
        ),
        migrations.RemoveField(
            model_name='officetransfer',
            name='from_date_bs',
        ),
    ]
