# Generated by Django 5.2.7 on 2026-07-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0013_leaverequest_attendancerecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="attendance_mark",
            field=models.CharField(
                blank=True,
                choices=[
                    ("on_time", "On Time"),
                    ("late", "Late"),
                    ("absent", "Absent"),
                ],
                default="on_time",
                max_length=12,
            ),
        ),
    ]
