# Generated by Django 5.2.7 on 2025-10-12 07:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('province', models.CharField(choices=[('01', 'Koshi Province'), ('02', 'Madhesh Province'), ('03', 'Bagmati Province'), ('04', 'Gandaki Province'), ('05', 'Lumbini Province'), ('06', 'Karnali Province'), ('07', 'Sudurpaschim Province')], max_length=2)),
                ('established_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Directorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='directorates', to='organizations.ministry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('province', models.CharField(choices=[('01', 'Koshi Province'), ('02', 'Madhesh Province'), ('03', 'Bagmati Province'), ('04', 'Gandaki Province'), ('05', 'Lumbini Province'), ('06', 'Karnali Province'), ('07', 'Sudurpaschim Province')], max_length=2)),
                ('directorate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offices', to='organizations.directorate')),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offices', to='organizations.ministry')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
