# Generated by Django 5.2.7 on 2025-10-14 09:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_rename_start_date_ad_officetransfer_transfer_date_ad_and_more'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='directorate',
        ),
        migrations.RemoveField(
            model_name='office',
            name='ministry',
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('org_type', models.CharField(choices=[('ministry', 'Ministry'), ('department', 'Department'), ('directorate', 'Directorate'), ('office', 'Office')], max_length=30)),
                ('province', models.CharField(choices=[('01', 'Koshi Province'), ('02', 'Madhesh Province'), ('03', 'Bagmati Province'), ('04', 'Gandaki Province'), ('05', 'Lumbini Province'), ('06', 'Karnali Province'), ('07', 'Sudurpaschim Province')], max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('established_date_ad', models.DateField(blank=True, null=True)),
                ('established_date_bs', models.CharField(blank=True, max_length=10, null=True)),
                ('parent_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_orgs', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Directorate',
        ),
        migrations.DeleteModel(
            name='Ministry',
        ),
        migrations.DeleteModel(
            name='Office',
        ),
    ]
