# Generated by Django 5.2.7 on 2026-06-28 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_employee_hr_foundation'),
        ('organizations', '0004_organization_foundation'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganization',
            name='head_employee',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='organization',
            name='head_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_organizations', to='employees.employee'),
        ),
    ]
