# Generated by Django 5.2.7 on 2026-06-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_organization_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorganization',
            name='org_type',
            field=models.CharField(choices=[('ministry', 'Ministry / मन्त्रालय'), ('department', 'Department / विभाग'), ('directorate', 'Directorate / निर्देशनालय'), ('division', 'Division / महाशाखा'), ('branch', 'Branch / शाखा'), ('section', 'Section / उपशाखा'), ('unit', 'Unit / इकाई'), ('office', 'Office / कार्यालय')], max_length=30),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('ministry', 'Ministry / मन्त्रालय'), ('department', 'Department / विभाग'), ('directorate', 'Directorate / निर्देशनालय'), ('division', 'Division / महाशाखा'), ('branch', 'Branch / शाखा'), ('section', 'Section / उपशाखा'), ('unit', 'Unit / इकाई'), ('office', 'Office / कार्यालय')], max_length=30),
        ),
    ]
