"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import Csv, config
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    "SECRET_KEY",
    default="django-insecure-g-hrms-backend-secret-key-change-me-in-production-2025-!@#abc-please-change-me",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DJANGO_DEBUG", default=True, cast=bool)

ALLOWED_HOSTS = config(
    "ALLOWED_HOSTS",
    default="localhost,127.0.0.1,testserver",
    cast=Csv(),
)
# Add Render's external hostname if available
render_hostname = config("RENDER_EXTERNAL_HOSTNAME", default="")
if render_hostname:
    ALLOWED_HOSTS.append(render_hostname)

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True
SECURE_HSTS_SECONDS = config("SECURE_HSTS_SECONDS", default=(0 if DEBUG else 31536000), cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = config("SECURE_HSTS_INCLUDE_SUBDOMAINS", default=(not DEBUG), cast=bool)
SECURE_HSTS_PRELOAD = config("SECURE_HSTS_PRELOAD", default=(not DEBUG), cast=bool)
SECURE_SSL_REDIRECT = config("SECURE_SSL_REDIRECT", default=(not DEBUG), cast=bool)
SESSION_COOKIE_SECURE = config("SESSION_COOKIE_SECURE", default=(not DEBUG), cast=bool)
CSRF_COOKIE_SECURE = config("CSRF_COOKIE_SECURE", default=(not DEBUG), cast=bool)

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # third-party
    "rest_framework",
    "corsheaders",
    "drf_spectacular",
    "concurrency",
    "simple_history",
    # local apps
    # "employees",
    "employees.apps.EmployeesConfig",
    "organizations",
    "account",
    "authentication.apps.AuthenticationConfig",
    "documents.apps.DocumentsConfig",
    "payroll",
]

AUTH_USER_MODEL = "account.User"

REST_FRAMEWORK = {
    "EXCEPTION_HANDLER": "core.exceptions.api_exception_handler",
    # Bearer PASETO access tokens. Organization and employee APIs apply explicit
    # role-aware permissions; login/signup opt out with authentication_classes=[].
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "authentication.authentication.PasetoAuthentication",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_PAGINATION_CLASS": "employees.pagination.EmployeePagination",
    "PAGE_SIZE": 10,
    "DEFAULT_SCHEMA_CLASS":"drf_spectacular.openapi.AutoSchema",
    # Per-IP throttling for the anonymous signup/OTP endpoints. These are an
    # outer guard; the signup service also enforces per-account OTP attempt and
    # resend limits.
    "DEFAULT_THROTTLE_RATES": {
        "signup": config("THROTTLE_SIGNUP", default="10/min"),
        "signup_verify": config("THROTTLE_SIGNUP_VERIFY", default="10/min"),
        "signup_resend": config("THROTTLE_SIGNUP_RESEND", default="5/min"),
    },
}

SPECTACULAR_SETTINGS = {
    "TITLE": "G-HRMS API",
    "DESCRIPTION": (
        "Government HRMS backend API.\n\n"
        # "## Authentication\n"
        # "1. `POST /api/auth/csrf/` to obtain a CSRF token (cookie + body).\n"
        # "2. `POST /api/auth/signup/` then `POST /api/auth/signup/verify/` with "
        # "the e-mailed OTP to register (account is created in the `invited` "
        # "state).\n"
        # "3. `POST /api/auth/login/` with `email` + `password` to receive an "
        # "`access_token` (PASETO) and an HttpOnly refresh cookie.\n"
        # "4. Click **Authorize** (top right) and paste the `access_token` to "
        # "call protected endpoints. Use `POST /api/auth/refresh/` to rotate it.\n"
    ),
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SORT_OPERATIONS": False,
    "ENUM_NAME_OVERRIDES": {
        "AccountStatusEnum": "account.models.User.Status",
        "EmployeeStatusEnum": "employees.models.Employee.Status",
        "EmploymentTypeEnum": "employees.models.Employee.EmploymentType",
        "OfficeTransferStatusEnum": "employees.models.OfficeTransfer.Status",
    },
    "TAGS": [
        {"name": "Authentication", "description": "Signup (OTP), login, refresh, logout."},
        {"name": "Administration", "description": "Superadmin account management (status changes)."},
        {"name": "Employees", "description": "Employee records and office transfers."},
        {"name": "Office Transfers", "description": "Employee movement and appointment records."},
        {"name": "Organizations", "description": "Government organization hierarchy and heads."},
        {"name": "Services", "description": "Civil-service classifications."},
        {"name": "Categories", "description": "Categories within a civil service."},
        {"name": "Subcategories", "description": "Subcategories within a category."},
        {"name": "Levels", "description": "Gazetted and non-gazetted employee levels."},
        {"name": "Positions", "description": "Posts linked to service taxonomy and levels."},
        {"name": "Payroll", "description": "Payroll runs, salary entries, and payment settlement records."},
    ],
    "SWAGGER_UI_SETTINGS": {
        "persistAuthorization": True,
        "displayRequestDuration": True,
        "filter": True,
        "docExpansion": "none",
    },
}

MIDDLEWARE = [
    "core.middleware.RequestContextMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "core.middleware.CurrentUserMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# Only these direct peers may supply X-Forwarded-For. Keep empty in local
# development; configure the load balancer/reverse-proxy IPs in production.
TRUSTED_PROXY_IPS = tuple(
    ip.strip()
    for ip in config("TRUSTED_PROXY_IPS", default="").split(",")
    if ip.strip()
)

LOG_LEVEL = config("LOG_LEVEL", default="INFO").upper()

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "request_context": {
            "()": "core.logging.RequestContextFilter",
        },
    },
    "formatters": {
        "json": {
            "()": "core.logging.JsonFormatter",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "filters": ["request_context"],
            "formatter": "json",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "ghrms": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
    },
}
AUTH_MAX_FAILED_LOGIN_ATTEMPTS = config(
    "AUTH_MAX_FAILED_LOGIN_ATTEMPTS",
    default=5,
    cast=int,
)

AUTH_LOCKOUT_DURATION = timedelta(
    minutes=config(
        "AUTH_LOCKOUT_MINUTES",
        default=15,
        cast=int
    )
)

AUTH_REFRESH_TOKEN_LIFETIME = timedelta(
    days=config("AUTH_REFRESH_TOKEN_DAYS", default=7, cast=int)
)

AUTH_REFRESH_COOKIE_NAME = config(
    "AUTH_REFRESH_COOKIE_NAME",
    default=("ghrms_refresh" if DEBUG else "__Host-ghrms_refresh"),
)
AUTH_REFRESH_COOKIE_SECURE = config(
    "AUTH_REFRESH_COOKIE_SECURE",
    default=not DEBUG,
    cast=bool,
)
AUTH_REFRESH_COOKIE_SAMESITE = config(
    "AUTH_REFRESH_COOKIE_SAMESITE",
    default="Strict",
)
AUTH_REFRESH_COOKIE_PATH = "/"

PASETO_PRIVATE_KEY_PATH = BASE_DIR / config(
    "PASETO_PRIVATE_KEY_PATH",
    default=".secrets/paseto/private.pem",
)

PASETO_PUBLIC_KEY_PATH = BASE_DIR / config(
    "PASETO_PUBLIC_KEY_PATH",
    default=".secrets/paseto/public.pem",
)

# Read PASETO keys from environment variables if available (for Render)
PASETO_PRIVATE_KEY = config("PASETO_PRIVATE_KEY", default="")
PASETO_PUBLIC_KEY = config("PASETO_PUBLIC_KEY", default="")

PASETO_ISSUER = config(
    "PASETO_ISSUER",
    default="g-hrms-backend",
)

PASETO_AUDIENCE = config(
    "PASETO_AUDIENCE",
    default="g-hrms-api",
)

PASETO_ACCESS_TOKEN_LIFETIME = timedelta(
    minutes=config(
        "PASETO_ACCESS_TOKEN_MINUTES",
        default=5,
        cast=int,
    )
)

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "template"],  # 👈 include this
        # "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
if DEBUG:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    import dj_database_url
    database_url = config("DATABASE_URL", default="")
    if database_url:
        DATABASES = {
            "default": dj_database_url.parse(database_url)
        }
    else:
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.sqlite3",
                "NAME": BASE_DIR / "db.sqlite3",
            }
        }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
]
# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


CORS_ALLOWED_ORIGINS = config(
    "CORS_ALLOWED_ORIGINS",
    default="http://localhost:8080,http://127.0.0.1:8080",
    cast=Csv(),
)
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = config(
    "CSRF_TRUSTED_ORIGINS",
    default="http://localhost:8080,http://127.0.0.1:8080",
    cast=Csv(),
)

PASETO_CLOCK_SKEW_SECONDS = config(
    "PASETO_CLOCK_SKEW_SECONDS",
    default=30,
    cast=int
)


# Cache backend
# Used for the pending-signup/OTP store and DRF throttling. Redis is the
# production backend (shared across processes/workers, atomic TTLs). When no
# REDIS_URL is configured we fall back to a per-process in-memory cache, which
# is only suitable for local development and single-process test runs.
REDIS_URL = config("REDIS_URL", default="")

if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "ghrms-local",
        }
    }


# Email / SMTP
# Government deployments use their own SMTP relay (e.g. an agency mail gateway),
# never a personal Gmail account. Everything here is environment-driven: set
# EMAIL_HOST and credentials in production. In DEBUG we print emails to the
# console so OTPs are visible without a mail server.
EMAIL_BACKEND = config(
    "EMAIL_BACKEND",
    default=(
        "django.core.mail.backends.console.EmailBackend"
        if DEBUG
        else "django.core.mail.backends.smtp.EmailBackend"
    ),
)
EMAIL_HOST = config("EMAIL_HOST", default="")
EMAIL_PORT = config("EMAIL_PORT", default=587, cast=int)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)
EMAIL_USE_SSL = config("EMAIL_USE_SSL", default=False, cast=bool)
EMAIL_TIMEOUT = config("EMAIL_TIMEOUT", default=10, cast=int)
DEFAULT_FROM_EMAIL = config(
    "DEFAULT_FROM_EMAIL",
    default="G-HRMS <no-reply@ghrms.local>",
)
SERVER_EMAIL = config("SERVER_EMAIL", default=DEFAULT_FROM_EMAIL)


# Signup OTP / pending-registration policy
# Credentials are never written to the database until the email is proven via
# OTP. Until then they live only in the cache, with the password already hashed.
AUTH_SIGNUP_OTP_LENGTH = config(
    "AUTH_SIGNUP_OTP_LENGTH",
    default=6,
    cast=int,
)
AUTH_SIGNUP_OTP_TTL = timedelta(
    minutes=config("AUTH_SIGNUP_OTP_TTL_MINUTES", default=10, cast=int)
)
AUTH_SIGNUP_OTP_MAX_ATTEMPTS = config(
    "AUTH_SIGNUP_OTP_MAX_ATTEMPTS",
    default=5,
    cast=int,
)
AUTH_SIGNUP_OTP_RESEND_COOLDOWN = timedelta(
    seconds=config(
        "AUTH_SIGNUP_OTP_RESEND_COOLDOWN_SECONDS",
        default=60,
        cast=int,
    )
)
AUTH_SIGNUP_OTP_MAX_RESENDS = config(
    "AUTH_SIGNUP_OTP_MAX_RESENDS",
    default=3,
    cast=int,
)
AUTH_SIGNUP_CACHE_PREFIX = config(
    "AUTH_SIGNUP_CACHE_PREFIX",
    default="ghrms:signup:pending",
)

# Reject e-mail addresses whose domain cannot receive mail before sending an
# OTP. Anti-abuse only, fail-open on DNS errors. Enabled outside DEBUG so local
# development and tests are not coupled to a working resolver.
AUTH_SIGNUP_VERIFY_EMAIL_DOMAIN = config(
    "AUTH_SIGNUP_VERIFY_EMAIL_DOMAIN",
    default=not DEBUG,
    cast=bool,
)
AUTH_SIGNUP_EMAIL_DNS_TIMEOUT = config(
    "AUTH_SIGNUP_EMAIL_DNS_TIMEOUT",
    default=3.0,
    cast=float,
)

# --- Document malware scanning (ClamAV) ---------------------------------
# Uploaded document versions are scanned by a clamd daemon. A version may only
# be VERIFIED once its scan_status is CLEAN. Disabled by default in DEBUG so
# local development and tests do not require a running daemon; enable it in
# real environments by pointing CLAMAV_* at the daemon.
DOCUMENT_SCAN_ENABLED = config(
    "DOCUMENT_SCAN_ENABLED",
    default=not DEBUG,
    cast=bool,
)
# Scan automatically after each upload (via transaction.on_commit). When off,
# scanning runs only through the management command or the scan API.
DOCUMENT_SCAN_ON_UPLOAD = config(
    "DOCUMENT_SCAN_ON_UPLOAD",
    default=DOCUMENT_SCAN_ENABLED,
    cast=bool,
)
# Prefer a Unix socket when set; otherwise fall back to the TCP host/port.
CLAMAV_UNIX_SOCKET = config("CLAMAV_UNIX_SOCKET", default="")
CLAMAV_HOST = config("CLAMAV_HOST", default="127.0.0.1")
CLAMAV_PORT = config("CLAMAV_PORT", default=3310, cast=int)
CLAMAV_TIMEOUT = config("CLAMAV_TIMEOUT", default=30.0, cast=float)
